{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "supportportal.serviceAccountName" . }}
  labels:
{{ include "supportportal.labels" . | indent 4 }}
{{- end -}}
