stages:
- build
- push

variables:
  PYTHONPATH: /opt/maubot

build:
  image: dock.mau.dev/maubot/maubot
  stage: build
  except:
  - tags
  script:
  - python3 -m maubot.cli build -o xyz.maubot.$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA.mbp
  artifacts:
    paths:
    - "*.mbp"

build tags:
  image: docker:stable
  stage: build
  only:
  - tags
  script:
  - python3 -m maubot.cli build -o xyz.maubot.$CI_PROJECT_NAME-$CI_COMMIT_TAG.mbp
  artifacts:
    paths:
    - "*.mbp"

build docker:
  image: docker:stable
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA . -f supportportal/standalone/Dockerfile
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

push latest:
  image: docker:stable
  stage: push
  only:
  - master
  variables:
    GIT_STRATEGY: none
  script:
  - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
  - docker push $CI_REGISTRY_IMAGE:latest
